variables:
  # Not normally needed, but may be if some script uses `apt-get install`.
  DEBIAN_FRONTEND: noninteractive
  # Locale settings do not affect the build, but might affect tests.
  LC_ALL: C

  CI_REGISTRY_IMAGE: registry.gitlab.isc.org/isc-projects/images/bind9

  # Disabled warnings:
  # SC2039 - complains about local var: In POSIX sh, 'local' is undefined.
  SHELLCHECK_OPTS: "--exclude=SC2039"

stages:
  - test

shellcheck:
  stage: test
  image: "$CI_REGISTRY_IMAGE:debian-stretch-amd64"
  before_script:
    - sudo apt-get update
    - sudo apt-get -y install shellcheck
  script:
    - SCRIPTS="src/bin/keactrl/keactrl.in "
    - SCRIPTS+="src/bin/admin/kea-admin.in "
    - SCRIPTS+="src/bin/admin/admin-utils.sh "
    - SCRIPTS+="tools/cql_config "
    - SCRIPTS+="tools/sysrepo_config "
    - shellcheck ${SCRIPTS} ${SHELLCHECK_OPTS}

danger:
  stage: test
  image: registry.gitlab.isc.org/isc-projects/stork/ci-danger
  before_script:
    - export CI_MERGE_REQUEST_ID=$(git ls-remote -q origin merge-requests\*\head | grep $CI_COMMIT_SHA | sed 's/.*refs\/merge-requests\/\([0-9]*\)\/head/\1/g')
    - export CI_PROJECT_PATH=$CI_PROJECT_ID #some version of gitlab has problems with searching by project path
    - export DANGER_GITLAB_HOST=gitlab.isc.org
    - export DANGER_GITLAB_API_BASE_URL=https://gitlab.isc.org/api/v4
    - sysctl -w net.ipv6.conf.all.disable_ipv6=1
    - sysctl -w net.ipv6.conf.default.disable_ipv6=1
  script:
    - echo '149.20.48.126 gitlab.isc.org' >> /etc/hosts
    - gem install danger-commit_lint
    - danger --fail-on-errors=true --new-comment
